# Default values for aws-auth-reloader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cib0rg/aws-auth-reloader
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

awsRegion: us-west-2
# awsAccessKeyID: 
# awsSecretAccessKey: 

logLevel: "info"
dryRun: "false"

#tagPrefix: "foo:"
clusterName: "" # Mandatory

# Examples
protectedEntities: {}
  # - arn:aws:iam::123456789012:role/EKSNodeIamRole
  # - arn:aws:iam::123456789012:role/eksClusterRole
  # - arn:aws:iam::123456789012:user/vip-developer
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
